services:
  # Веб-сервис для обработки встреч
  meeting-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: meeting-processor-web
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/app/logs
      - ./web_uploads:/app/web_uploads
      - ./web_output:/app/web_output
      - ./config.json:/app/config.json:ro
      - ./api_keys.json:/app/api_keys.json:ro
      - ./templates_config.json:/app/templates_config.json:ro
      - ./team_config.json:/app/team_config.json:ro
    environment:
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - meeting-network

  # Telegram бот
  meeting-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: meeting-processor-bot
    volumes:
      - ./logs:/app/logs
      - ./temp_bot_files:/app/temp_bot_files
      - ./meeting_output:/app/meeting_output
      - ./bot_config.json:/app/bot_config.json:ro
      - ./api_keys.json:/app/api_keys.json:ro
      - ./templates_config.json:/app/templates_config.json:ro
      - ./team_config.json:/app/team_config.json:ro
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    restart: unless-stopped
    networks:
      - meeting-network

networks:
  meeting-network:
    driver: bridge

volumes:
  logs:
    driver: local
