{{- if .Values.bot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meeting-processor.fullname" . }}-bot
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "meeting-processor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: bot
    app.kubernetes.io/part-of: meeting-processor
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.bot.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "meeting-processor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "meeting-processor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: bot
        app.kubernetes.io/part-of: meeting-processor
        environment: {{ .Values.environment }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: bot
        image: {{ include "meeting-processor.bot.image" . }}
        imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "meeting-processor.fullname" . }}-secrets
              key: telegram-bot-token
        - name: DEEPGRAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "meeting-processor.fullname" . }}-secrets
              key: deepgram-api-key
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "meeting-processor.fullname" . }}-secrets
              key: claude-api-key
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: bot-temp
          mountPath: /app/temp_bot_files
        - name: bot-output
          mountPath: /app/meeting_output
        - name: secrets
          mountPath: /app/bot_config.json
          subPath: bot_config.json
          readOnly: true
        - name: secrets
          mountPath: /app/api_keys.json
          subPath: api_keys.json
          readOnly: true
        - name: config
          mountPath: /app/templates_config.json
          subPath: templates_config.json
          readOnly: true
        - name: secrets
          mountPath: /app/team_config.json
          subPath: team_config.json
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.bot.resources.requests.memory }}
            cpu: {{ .Values.bot.resources.requests.cpu }}
          limits:
            memory: {{ .Values.bot.resources.limits.memory }}
            cpu: {{ .Values.bot.resources.limits.cpu }}
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: {{ .Values.bot.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.bot.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.bot.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.bot.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: {{ .Values.bot.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.bot.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.bot.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.bot.readinessProbe.failureThreshold }}
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "meeting-processor.fullname" . }}-logs
      - name: bot-temp
        persistentVolumeClaim:
          claimName: {{ include "meeting-processor.fullname" . }}-bot-temp
      - name: bot-output
        persistentVolumeClaim:
          claimName: {{ include "meeting-processor.fullname" . }}-bot-output
      - name: config
        configMap:
          name: {{ include "meeting-processor.fullname" . }}-config
      - name: secrets
        secret:
          secretName: {{ include "meeting-processor.fullname" . }}-secrets
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
{{- end }}