apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meeting-processor.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meeting-processor.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values - should be provided via external secret management
  deepgram-api-key: {{ .Values.secrets.deepgramApiKey | b64enc | quote }}
  claude-api-key: {{ .Values.secrets.claudeApiKey | b64enc | quote }}
  telegram-bot-token: {{ .Values.secrets.telegramBotToken | b64enc | quote }}
stringData:
  api_keys.json: |
    {
      "deepgram_api_key": {{ .Values.secrets.deepgramApiKey | quote }},
      "claude_api_key": {{ .Values.secrets.claudeApiKey | quote }}
    }
  bot_config.json: |
    {
      "telegram_bot_token": {{ .Values.secrets.telegramBotToken | quote }},
      "allowed_users": {{ .Values.secrets.botConfig.allowedUsers | toJson }},
      "max_file_size": {{ .Values.secrets.botConfig.maxFileSize }},
      "supported_formats": {{ .Values.secrets.botConfig.supportedFormats | toJson }}
    }
  team_config.json: |
    {
      "teams": {{ .Values.secrets.teamConfig.teams | toJson }}
    }