{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meeting-processor.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "meeting-processor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: meeting-processor
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "meeting-processor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "meeting-processor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: meeting-processor
        environment: {{ .Values.environment }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: web
        image: {{ include "meeting-processor.web.image" . }}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.web.service.targetPort }}
          name: http
          protocol: TCP
        env:
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_APP
          value: "wsgi.py"
        - name: PYTHONPATH
          value: "/app"
        - name: GUNICORN_WORKERS
          value: {{ .Values.web.gunicorn.workers | quote }}
        - name: GUNICORN_THREADS
          value: {{ .Values.web.gunicorn.threads | quote }}
        - name: GUNICORN_TIMEOUT
          value: {{ .Values.web.gunicorn.timeout | quote }}
        - name: GUNICORN_MAX_REQUESTS
          value: {{ .Values.web.gunicorn.maxRequests | quote }}
        - name: GUNICORN_MAX_REQUESTS_JITTER
          value: {{ .Values.web.gunicorn.maxRequestsJitter | quote }}
        - name: DEEPGRAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "meeting-processor.fullname" . }}-secrets
              key: deepgram-api-key
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "meeting-processor.fullname" . }}-secrets
              key: claude-api-key
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: web-uploads
          mountPath: /app/web_uploads
        - name: web-output
          mountPath: /app/web_output
        - name: config
          mountPath: /app/config.json
          subPath: config.json
          readOnly: true
        - name: config
          mountPath: /app/templates_config.json
          subPath: templates_config.json
          readOnly: true
        - name: config
          mountPath: /app/gunicorn.conf.py
          subPath: gunicorn.conf.py
          readOnly: true
        - name: secrets
          mountPath: /app/api_keys.json
          subPath: api_keys.json
          readOnly: true
        - name: secrets
          mountPath: /app/team_config.json
          subPath: team_config.json
          readOnly: true
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.web.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.web.readinessProbe | nindent 10 }}
        startupProbe:
          {{- toYaml .Values.web.startupProbe | nindent 10 }}
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "meeting-processor.fullname" . }}-logs
      - name: web-uploads
        persistentVolumeClaim:
          claimName: {{ include "meeting-processor.fullname" . }}-web-uploads
      - name: web-output
        persistentVolumeClaim:
          claimName: {{ include "meeting-processor.fullname" . }}-web-output
      - name: config
        configMap:
          name: {{ include "meeting-processor.fullname" . }}-config
      - name: secrets
        secret:
          secretName: {{ include "meeting-processor.fullname" . }}-secrets
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
{{- end }}